# vol
volume=110
# Scale to exactly 2x
# window-scale=2

# Disable automatic aspect ratio maintenance for window
# keepaspect-window=yes

# Center the window on screen
geometry=50%:50%

# speed
speed=1.2

# no window decoration
no-border
