[modules]
left = ["Workspaces"]
center = ["Tempo"]
right = [["Tray", "Privacy", "Settings"]]

# [workspaces]
# workspace_names = ["1 ", "2 ", "3", "4 ", "5 ", "6", "7", "8", "9 ", "10 "]

[tempo]
clock_format = "%I:%M %p"

[settings]
audio_indicator_format = "IconAndPercentage"

[appearance]
font_name = "JetBrainsMono Nerd Font"
workspace_colors = [{ base = "#e0af68", text = "#1a1b26" }]
